apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ethis-argo-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cigbe00/ethis-service
    targetRevision: HEAD
    path: manifest
  destination: 
    server: https://kubernetes.default.svc
    namespace: ethis-prod
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true