apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: 381492145015.dkr.ecr.us-east-1.amazonaws.com/ethis_interview_ecs:66
        ports: 
        - containerPort: 8090


# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: myapp-service
#   namespace: argocd
# spec:
#   type: LoadBalancer
#   ports:
#   - name: http
#     port: 8080
#     targetPort: 8090
#     protocol: TCP
#   selector:
#     app: cicd-app