apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ci-cd-app
spec:
  replicas: 2
  selector:
    mactchLabels:
      app: my-ci-cd-app
  template:
    metadata:
      labels:
        app: my-ci-cd-app
    spec:
      containers:
      - name: my-ci-cd-app
        image: ****************.dkr.ecr.us-east-2.amazonaws.com/ethis_interview_ecs:54
        ports: 
        - containerPort: 80

apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: argocd
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: cicd-app